### ISSUE TITLE
re: GPU

### ISSUE THREAD

**Issue by drozzy** [ur-whitelab/hoomd-tf#102]
How did you guys install GPU support for hoomd?

I know this is unrelated to your project, but I figured you must have ran into this issue.

I tried compiling it and get this at the end:

```
HOOMD-blue v2.8.1-26-gef08be936 CUDA (10.2) DOUBLE HPMC_MIXED MPI SSE SSE2 SSE3 SSE4_1 SSE4_2 AVX AVX2 
Compiled: 11/26/2019
Copyright (c) 2009-2019 The Regents of the University of Michigan.
-----

system has unsupported display driver / cuda driver combination
HOOMD-blue is running on the CPU
<hoomd.context.SimulationContext object at 0x7f2334d383c8>

```

**Comment by RainierBarrett** [comment]
When you installed HOOMD-blue, did you not compile with CUDA? (`-DENABLE_CUDA=ON`?) That's what it looks like is going on here. Check out the HOOMD-blue compilation guide: https://hoomd-blue.readthedocs.io/en/v2.5.0/compiling.html

Here's the spot in our install guide where we talk about manual compilation with HOOMD-blue, if you want to start from scratch: https://github.com/ur-whitelab/hoomd-tf#compiling-with-hoomd-blue

**Comment by drozzy** [comment]
Thanks I'll give it a go.
