### ISSUE TITLE
Cuda requirements

### ISSUE THREAD

**Issue by moradza** [ur-whitelab/hoomd-tf#104]
I am using cuda 10 on a cluster, and I get the following error, how can I remove it,

Could NOT find CUDA: Found unsuitable version "9.2", but required is exact
  version "9.0" (found /usr/local/cuda-9.2)

**Comment by RainierBarrett** [comment]
You are trying to compile against an incompatible version of CUDA. You will need to load or install the exact CUDA version required, which is 9.0, and then compile.

**Comment by whitead** [comment]
Closing this for now. Let us know if you still need help
