### ISSUE TITLE
Evaluate migrating to TF 2.0

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/hoomd-tf#110]

**Comment by RainierBarrett** [comment]
So here's a really rough idea of what HTF might look like to use with TF2.0. The first bit of this file is an example of how to use TF2.0 generally, and the second half is how I envisioned we would ask users to interact with it.
[LJ_example.py.txt](https://github.com/ur-whitelab/hoomd-tf/files/4428401/LJ_example.py.txt)

**Comment by whitead** [comment]
Thanks for putting this together @RainierBarrett. There seems to be a lot of structure. Is it correct that you must have a model class and define separately a train_step function to complete the graph?

**Comment by whitead** [comment]
Conclusion is -> we're interested porting but want to evaluate jax and/or other options.
