### ISSUE TITLE
Either treat correctly or error on skewed 3D boxes 

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/hoomd-tf#111]

**Comment by RainierBarrett** [comment]
Currently the way boxes are read does not work for skewed 3D boxes. We ignore the off-diagonal terms in the HOOMD box matrix. Either do out the math so skewed boxes work, or add an error when skewed boxes are fed in.

**Comment by whitead** [comment]
Throw error if skewed here https://github.com/ur-whitelab/hoomd-tf/blob/master/htf/utils.py#L445 and https://github.com/ur-whitelab/hoomd-tf/blob/master/htf/graphbuilder.py#L181

**Comment by whitead** [comment]
Addressed by #213
