### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by hgandhi2411** [ur-whitelab/hoomd-tf#121]

**Comment by whitead** [comment]
Thoughts on technology? We can use the `Dockerfile` as a starting point https://github.com/ur-whitelab/hoomd-tf/blob/master/Dockerfile

**Comment by hgandhi2411** [comment]
I only know how to use travis but we can explore other technology like github actions maybe.

**Comment by whitead** [comment]
Solved by #232
