### ISSUE TITLE
Add config options and test XLA benchmarks

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/hoomd-tf#14]
XLA should drastically help for CG mapping operators code and other multistep complex code

**Comment by whitead** [comment]
Maybe try adding to [here](https://github.com/ur-whitelab/hoomd-tf/blob/master/tensorflow_plugin/tfmanager.py#L181)

**Comment by RainierBarrett** [comment]
This is done but I haven't run the benchmarks yet. Do we have a script we expect to get a lot of speedup from XLA?

**Comment by RainierBarrett** [comment]
Preliminary results show speedup around 2x with a large NN (50 nodes/layer, 5 hidden layers) at a few different values for N_particles. Benchmarking still running for larger systems but code should be all set.
