### ISSUE TITLE
Update compute functions to use graph box

### ISSUE THREAD

**Issue by hgandhi2411** [ur-whitelab/hoomd-tf#159]
Update these functions so that the box size is inferred from graph.box and doesn't need the system argument.
- [x] compute_nlist
- [x] htf.center_of_mass

**Comment by whitead** [comment]
- [ ] Modify Code
- [ ] Update tests to use new syntax
- [ ] Revisit tutorials to update to new syntax

**Comment by whitead** [comment]
Addressed by #175
