### ISSUE TITLE
Put hoomd-tf description on whitelab software page

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/hoomd-tf#18]

**Comment by hgandhi2411** [comment]
I've added hoomd-tf to the software page. Please take a look @whitead.

**Comment by whitead** [comment]
Can you get a transparent PNG for the image and put hoomd-tf at the top of the computational chemistry section.

**Comment by hgandhi2411** [comment]
Made the background for png transparent and put hoomd-tf at the top of comp chem software list.

**Comment by whitead** [comment]
Looks good!
