### ISSUE TITLE
[JOSS] Quickstart

### ISSUE THREAD

**Issue by RMeli** [ur-whitelab/hoomd-tf#185]
The [quickstart tutorial](https://hoomd-tf.readthedocs.io/en/latest/quickstart.html) throws the following errors:

* `NameError: name 'energy' is not defined`
* `NameError: name 'hoomd' is not defined`

`import hoomd` is missing, and `energy` is not defined (`particle_energy` instead?).

---

[JOSS review](https://github.com/openjournals/joss-reviews/issues/2367)

**Comment by whitead** [comment]
Thanks for doing our review! We've addressed this one with #188. Please close if satisfied or let me know if you have other concerns.

**Comment by RMeli** [comment]
LGTM, thanks for addressing this!
