### ISSUE TITLE
Add doc and conditional imports for trajectory parsing

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/hoomd-tf#190]
The trajectory parsing requires MDAnalysis, which is not mentioned in install. Please make the following changes:

- [x] Add doc section about trajectory parsing
- [x] Mention in install MDAnalysis is optional dependency, link to doc section about trajectory parsing
- [x] Make trajectory unit test conditional on MDAnalysis by using try/except import

**Comment by malramsay64** [comment]
[This](https://docs.pytest.org/en/latest/reference.html#pytest-importorskip-ref) might be helpful for the tests being conditional on imports
