### ISSUE TITLE
[JOSS] Paper

### ISSUE THREAD

**Issue by RMeli** [ur-whitelab/hoomd-tf#192]
I think the manuscript is good. I only have a few comments about the references:

* Reference #1 (Abadi et al., 2015) contains spurious `~`
* Reference #5 (Eastman, 2018) is missing a link? It should probably link to [openmm-nn](https://github.com/openmm/openmm-nn)
* Some reference that should be part of the text are still appearing within parenthesis (`For example (Rupp, Tkatchenko, Müller, & Anatole Von Lilienfeld, 2012) and (Botu & Ramprasad, 2015) are benchmark works...`). I'm not sure if there is a way to remove them...

I'm also wondering if a few more reference should be included, especially about force-matching, force-field biasing/learning and collective variables?

---
[JOSS review](https://github.com/openjournals/joss-reviews/issues/2367)

**Comment by RainierBarrett** [comment]
Thanks for your review. I'm not really familiar with doing these citations in markdown, so I'm not sure about the parentheses either. I pushed an updated paper/bib to the joss-paper-branch to address the rest of these points. Let us know if you have any other comments!

**Comment by RMeli** [comment]
Thanks @RainierBarrett . I'll investigate how to deal with references within the text, but it seems that the current changes broke the references. I think the square brackets `[]` were needed?

See the problem here:
> [ 👉 Check article proof 📄 👈 ](https://github.com/openjournals/joss-papers/blob/joss.02367/joss.02367/10.21105.joss.02367.pdf)

**Comment by RMeli** [comment]
According to the [Example paper and bibliography](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) it looks like `@reference` prints the reference within the text while `[@author:2001]` prints the reference within parentheses (if I understand correctly).  I think the `` are just there to render the example as code? It's a bit confusing...

**Comment by RainierBarrett** [comment]
@RMeli You're talking about this section, right?

```
For a quick reference, the following citation commands can be used:
- `@author:2001`  ->  "Author et al. (2001)"
- `[@author:2001]` -> "(Author et al., 2001)"
- `[@author1:2001; @author2:2001]` -> "(Author1 et al., 2001; Author2 et al., 2002)"
```

That's strange, because all of our refs are in the style of the first bullet there, but I think they were showing up as parentheticals the first time... I'll play around with it and see what happens.

**Comment by RMeli** [comment]
@RainierBarrett yes, that's the section. If I'm not mistaken, before you had [@author:2001] (not \`[@author:2001]\`) and it was working. So I assume the \`\` are spurious (i.e. they were supposed to render to a code block in the documentation?)... I'd try using `@author:2001` for a reference within the text and `[@author:2001]` for a reference within parentheses (without ``).

**Comment by RainierBarrett** [comment]
Okay, yeah I was just confused because of the formatting thing going on in the example paper there. Latest push should address all these. Thanks!

**Comment by RMeli** [comment]
I agree it's quite confusing... =)

LGTM now, thanks for addressing the comments. I'll leave this open in case @malramsay64 has further comments.

**Comment by malramsay64** [comment]
The paper looks good to me as well
