### ISSUE TITLE
[JOSS] Community Guidelines

### ISSUE THREAD

**Issue by RMeli** [ur-whitelab/hoomd-tf#199]
Can you please add some [community guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines) to the repository?

---
[JOSS review](https://github.com/openjournals/joss-reviews/issues/2367)

**Comment by RainierBarrett** [comment]
PR #203 should address this. I'm PRing these into the readthedocs branch for now so we can get that included in the version bump with everything else once that's ready to go.

**Comment by RMeli** [comment]
Thanks, the code of conduct looks good! Can you please add some contribution guidelines as well? I think a few lines linking to the Issue and PR tabs are more than enough (unless you also have a mailing list/Slack channel/...)

> There should be clear guidelines for third-parties wishing to:
>
>  *  Contribute to the software
>  * Report issues or problems with the software
>  *  Seek support

**Comment by RMeli** [comment]
Commit 986cbc6 solves this issue for me, thanks. I'll close it unless @malramsay64 has any additional comments.

**Comment by malramsay64** [comment]
LGTM
