### ISSUE TITLE
[JOSS] Documentation and Readme

### ISSUE THREAD

**Issue by RMeli** [ur-whitelab/hoomd-tf#200]
The description on the documentation homepage is quite short (see [statement of need](https://joss.readthedocs.io/en/latest/review_criteria.html#a-statement-of-need)). Since the README contains a more detailed explanation, I think using the same explanation in both the README and the documentation would be beneficial.

Listing the main (and optional) dependencies mentioned in the documentation on the README would be helpful as well.

---
[JOSS review](https://github.com/openjournals/joss-reviews/issues/2367)

**Comment by RainierBarrett** [comment]
PR #202 should cover this. I'm PRing these into the readthedocs branch for now so we can get that included in the version bump with everything else once that's ready to go.

**Comment by RMeli** [comment]
Sounds good, thanks! LGTM

**Comment by RMeli** [comment]
I'll close this unless @malramsay64 has anything to add.

**Comment by malramsay64** [comment]
I have nothing to add LGTM
