### ISSUE TITLE
[JOSS] Tests and Benchmarks

### ISSUE THREAD

**Issue by malramsay64** [ur-whitelab/hoomd-tf#201]
There are a couple of currently undocumented files/functionality that are hiding away in the source code that I would like some clarification on.

- [x] The [test-cc directory](https://github.com/ur-whitelab/hoomd-tf/tree/master/htf/test-cc) that appears to contain some element of testing the C++ components. I can see it was intentional to create (#9 #48), so it looks to be an omission that there is no documentation of this test.

- [x] The [benchmarking directory](https://github.com/ur-whitelab/hoomd-tf/tree/master/htf/models/benchmarking) that contains a performance benchmark. There is definitely benefit to having a performance benchmark as a method of ensuring the appropriate hardware is being used.
---
[JOSS Review](https://github.com/openjournals/joss-reviews/issues/2367)

**Comment by RainierBarrett** [comment]
Hi @malramsay64. The test-cc directory is a remnant from early development. We have since moved to python testing for this functionality (see `test_compute` in test_tensorflow.py), so this should probably just be removed. Thanks for the catch. I'll work on adding some documentation around benchmarking.

**Comment by RainierBarrett** [comment]
Okay, #207 should address this. I don't know how but my git bash on windows got a little antsy so there's some wonky commit history going on.

**Comment by RMeli** [comment]
Addressed in #208 (superseding #207)

**Comment by RainierBarrett** [comment]
@RMeli and @malramsay64 #208 has been merged, should be all set!
