### ISSUE TITLE
box_size fails with 3D box read from .gsd file

### ISSUE THREAD

**Issue by RainierBarrett** [ur-whitelab/hoomd-tf#259]
Hi all! I'm working with reading from a .gsd trajectory in order to do CG mapping. I followed along with the example notebooks, but I get an issue when I try to apply the mapping and output the mapped particle positions. Attached is a MWE with two requisite .gsd files and a jupyter notebook. In the final cell of the notebook, if youcan manually feed in the correct `[16., 16., 16.]` for `box_size`, but in the examples I was following, it is fed in as `htf.box_size(box)`. However, if we print that out we can see that the third box dimension is coming out as zero, which causes `nan`s to show up for the mapped particle positions.

[box-size-mwe.zip](https://github.com/ur-whitelab/hoomd-tf/files/5877038/box-size-mwe.zip)

**Comment by whitead** [comment]
Hi @RainierBarrett thanks for pointing this out! I believe [this line](https://github.com/ur-whitelab/hoomd-tf/blob/2bfc45c0a9fd4c523fc3008eecc5948a6397c12e/htf/utils.py#L444) needs to be corrected to match [the box doc](https://hoomd-tf.readthedocs.io/en/latest/building_a_model.html#building-a-model). @hgandhi2411 or @geemi725 can one of you set-up a PR for this?

**Comment by hgandhi2411** [comment]
Addressed by #260
