### ISSUE TITLE
Make XLA on by default

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/hoomd-tf#53]
XLA speeds-up and seems to have no downsides. Any thoughts @RainierBarrett?

**Comment by RainierBarrett** [comment]
Yeah I don't think there's any particular reason not to keep it on. If we run into problems later we can always turn it back off.

**Comment by whitead** [comment]
Fixed by #76

**Comment by whitead** [comment]
Heta ran into problems with this. We should disable it by default because it's confusing when you get a not-implemented error without knowing you enabled XLA. @geemi725 could you undo this with a new PR? Thanks
