### ISSUE TITLE
Improve unit testing 

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/hoomd-tf#9]
- [x] Add C++ tests
- [ ] Add coverage analysis
- [ ] Add timing tests for assessing regression in performance

**Comment by whitead** [comment]
Feel free to split this across multiple milestones. Especially the timing tests. You can see examples of tests in [hoomd-blue/test](https://github.com/joaander/hoomd-blue/tree/master/hoomd/test)

**Comment by RainierBarrett** [comment]
We can run `pytest --cov=hoomd-tf/htf hoomd-tf/htf/test-py` to get code coverage reported, and for timing information, we can run [benchmark_xla.py](https://github.com/ur-whitelab/hoomd-tf/blob/master/htf/models/benchmarking/benchmark_xla.py). Despite its name, it can be used to benchmark with and without use of XLA, and records execution timesteps per second in a file when it's finished.

**Comment by whitead** [comment]
Closing it for now
