### ISSUE TITLE
Tutorial Notebooks

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/hoomd-tf#93]
Now that we have the ability to create/run models in a single python script, we should make a folder with some example jupyter notebooks. A great start would be the [quickstart](https://github.com/ur-whitelab/hoomd-tf#quickstart-tutorial) from the README.

**Comment by oktak** [comment]
Let me take this, the quickstart one ;)
How about name the folder be `examples`?

**Comment by whitead** [comment]
Closed by #95. Thank you @oktak!
