### ISSUE TITLE
Make conda release

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/hoomd-tf#96]
Can we make a proper conda release that people can install?

**Comment by whitead** [comment]
There are hoomd-blue GPU releases now.

**Comment by whitead** [comment]
@hgandhi2411 what's the status of this?

**Comment by hgandhi2411** [comment]
> @hgandhi2411 what's the status of this?
@whitead I was unable to solve the package incompatibilities on Azure pipelines. I have asked MolSSI software scientists to help with it.

**Comment by whitead** [comment]
@hgandhi2411 can you see how hoomd does theirs?

**Comment by hgandhi2411** [comment]
@whitead  I have looked at how hoomd does theirs but the problem is not with hoomd. The incompatibilities are coming from dependencies for tensorflow.

**Comment by whitead** [comment]
@hgandhi2411 Any update on this?

**Comment by whitead** [comment]
Too difficult with tensorflow not supporting conda
