### ISSUE TITLE
Converting gromacs all-atom trajectory to a hooomd gsd file

### ISSUE THREAD

**Issue by dilnoza92** [ur-whitelab/hoomd-tf#97]
Need a thorough documentation and a python script to convert an all-atom trajectory to a hoomd trajectory file.

**Comment by hgandhi2411** [comment]
Use mdanalysis to parse coordinates from trajectory files and parse it to graph feeddict. Test how this would work independent of hoomd-blue.

**Comment by whitead** [comment]
Remember to add MDAnalysis as dependency and be careful it doesn't bring in very recent version of tensorflow.

**Comment by hgandhi2411** [comment]
Addressed by #147
